// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNAMqvibvcX8233Qu4vFc4KjNBXLK6pNE',
    appId: '1:452820158591:web:0abd6f274cf04ca78ed74a',
    messagingSenderId: '452820158591',
    projectId: 'zg0ul-notes-app',
    authDomain: 'zg0ul-notes-app.firebaseapp.com',
    storageBucket: 'zg0ul-notes-app.appspot.com',
    measurementId: 'G-HMS9DC8JFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPI_Im_ewyQgAxTD7AUkPJbOoFRJzg5j4',
    appId: '1:452820158591:android:28d7fd5c212008c98ed74a',
    messagingSenderId: '452820158591',
    projectId: 'zg0ul-notes-app',
    storageBucket: 'zg0ul-notes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdcEL4M026HJCIyw1fZ5px_HHwFU_uJ-c',
    appId: '1:452820158591:ios:3eb6bb8a01ab2ca18ed74a',
    messagingSenderId: '452820158591',
    projectId: 'zg0ul-notes-app',
    storageBucket: 'zg0ul-notes-app.appspot.com',
    iosClientId: '452820158591-r1l66ajuujjjj9rabjv4k5or6ud5rlkk.apps.googleusercontent.com',
    iosBundleId: 'tech.zg0ul.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdcEL4M026HJCIyw1fZ5px_HHwFU_uJ-c',
    appId: '1:452820158591:ios:1b5e14412a3f704b8ed74a',
    messagingSenderId: '452820158591',
    projectId: 'zg0ul-notes-app',
    storageBucket: 'zg0ul-notes-app.appspot.com',
    iosClientId: '452820158591-mcqc4vjpsk3cs1rgcmq4ia1rjb9flb8i.apps.googleusercontent.com',
    iosBundleId: 'tech.zg0ul.mynotes.RunnerTests',
  );
}
